#### 예외와 예외 클래스

에러는 JVM 실행에 문제가 생겼다는 것으로 JVM 위에서 실행되는 프로그램을 아무리 견고하게 만들어도 결국 실행 불능이 된다. 자바에서는 에러 이외에 예외(exception)라고 부르는 오류가 있다. **예외란 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류**를 말한다. 예외가 발생되면 프로그램은 곧바로 종료된다는 점에서 에러와 동일하다. **예외는 예외 처리(Exception Handling)를 통해 프로그램을 종료하지 않고 정상 실행 상태가 유지**되도록 할 수 있다.

예외는 두 종류가 있다. 하나는 **일반 예외(Exception)**이고, 다른 하나는 **실행 예외(Runtime Exception)**이다. 일반 예외는 컴파일러 체크 예외라고도 하는데, 자바 소스를 컴파일하는 과정에서 예외 처리 코드 코드가 필요한지 검사하기 때문이다. 만약 예외 처리 코드가 없다면 컴파일 오류가 발생한다. 실행 예외는 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외를 말한다. **컴파일 시 예외 처리를 확인하는 차이**일 뿐, 두 가지 예외는 모두 예외 처리에 필요하다.

일반 예외와 실행 예외 클래스를 구별하는 방법은 일반 예외는 Exception을 상속받지만 Runtime Exception을 상속받지 않는 클래스들이고, 실행 예외는 다음과 같이 RuntimeException을 상속받은 클래스들이다. RuntimeException 역시 Exception을 상속받지만, JVM은 RuntimeException을 상속했는지 여부를 보고 실행 예외를 판단한다.

#### 실행 예외

실행 예외는 자바 컴파일러가 체크를 하지 않기에 오로지 개발자의 경험에 의해서 예외 처리 코드를 삽입해야 한다. 만약 개발자가 실행 예외에 대해 예외 처리 코드를 넣지 않았을 경우, 해당 예외가 발생하면 프로그램은 곧바로 종료된다.

##### NullPointerException

객체 참조가 없는 상태, 즉 null 값을 갖는 참조 변수고 객체 접근 연산자(.)를 사용했을 때 발생한다. **객체가 없는 상태에서 객체를 사용하려 했으니 예외가 발생**하는 것이다.

```java
String data = null;
System.out.println(data.toString());
```

##### ArrayIndexOutOfBoundsException

배열에서 인덱스 범위를 초과하여 사용할 경우 실행 예외인 java.lang.ArrayIndexOutOf-BoundsException이 발생한다.

##### NumberFormatException

문자열로 되어 있는 데이터를 숫자로 변경하는 경우가 자주 발생한다. 문자열을 숫자로 변환하는 방법은 여러 가지가 있지만 가장 많이 사용되는 코드는 다음과 같다.

| 반환 타입 | 메소드명(매개 변수)          | 설명                                 |
| --------- | ---------------------------- | ------------------------------------ |
| int       | Integer.parseInt(String s)   | 주어진 문자열을 정수로 변환해서 리턴 |
| double    | Double.parseDouble(String s) | 주어진 문자열을 실수로 변환해서 리턴 |

Integer와 Double은 포장(Wrapper) 클래스이다. 이 클래스의 정적 메소드인 parseXXX() 메소드를 이용하면 문자열을 숫자로 변환할 수 있다. 이 메소들은 매개값인 문자열이 숫자로 변환될 수 있다면 숫자를 리턴하지만, 숫자로 변환할 수 없는 문자가 포함되어 있다면 java.lang.NumberFormatException을 발생시킨다.

```java
String data = "a100";
int value = Integer.parseInt(data); // NumberFormatException 발생
```

data의 변수 "a100" 문자열은 숫자로 변환할 수 없기에 다음과 같이 NumberFormatException이 발생한다.

##### ClassCastException

타입 변환(Casting)은 상위 클래스와 하위 클래스 간에 발생하고 구현 클래스와  인터페이스 간에도 발생한다. 이러한 관계아 아니라면 클래스는 다른 클래스로 타입 변환할 수 없다. 억지로 타입 변환을 시도할 경우 ClassCastException이 발생한다.

대입된 객체가 아닌 클래스 타입으로 타입 변환을 하면 ClassCastException이 발생한다.

```java
Animal animal = new Dog();
Cat cat = (Cat) animal;
```

ClassCastException을 발생시키지 않으려면 타입 변환 전에 타입 변환이 가능한지 instanceof 연산자로 확인하는 것이 좋다. instanceof 연산의 결과가 true이면 좌항 객체를 우항 타입으로 변환이 가능하다는 것이다.

#### 예외 처리 코드

**프로그램에서 예외가 발생했을 경우 프로그램의 갑작스러운 종료를 막고, 정상 실행을 유지할 수 있도록 처리하는 코드**를 예외 처리 코드라고 한다. 자바 컴파일러는 소스 파일을 컴파일할 때 **일반 예외**가 발생할 가능성이 있는 코드를 발견하면 컴파일 오류를 발생시켜 개발자로 하여금 강제적으로 예외 처리 코드를 작성하도록 요구한다. 그러나 실행 예외는 컴파일러가 체크해주지 않기 때문에 예외 처리 코드를 개발자의 경험을 바탕으로 작성해야 한다. 예외 처리 코드는 try-catch-finally 블록을 이용한다. try-catch-finally 블록은 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해준다.

```java
try {

} catch(예외클래스 e) {
	// 예외 처리
} finally {
	// 항상 실행
}
```

try 블록에는 예외 발생 가능 코드가 위치한다. try 블록의 코드가 예외 발생 없이 정상 실행되면 catch 블록의 코드는 실행되지 않고 finally 블록의 코드를 실행한다. 만약 try 블록의 코드에서 예외가 발생하면 즉시 실행을 멈추고 catch 블록으로 이동하여 예외 처리 코드를 실행한다. finally 블록은 예외 발생 여부와 상관없이 항상 실행할 내용이 있을 경우에만 작성해주면 된다. try블록과 catch블록에서 return문을 사용하더라도 finally 블록은 항상 실행된다.



#### 예외 종류에 따른 처리 코드

##### 다중 catch

try 블록 내부에슨 다양한 종류의 예외가 발생할 수 있따. 발생하는 예외별로 예외 처리 코드를 다르게 하려면 다중 catch 블록을 작성하면 된다. catch 블록의 예외 클래스 타입은 try 블록에서 발생된 예외의 종류를 말하는데, try 블록에서 해당 타입의 예외가 발생하면 catch 블록을 실행하도록 되어 있다.

```java
try {
} catch(예외클래스 e) {
} catch(예외클래스 e) {
}
```

**catch 블록이 여러 개라 할지라도 단 하나의 catch 블록만 실행**된다. 그 이유는 try 블록에서 동시 다발적으로 예외가 발생하지 않고, ,하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문이다.

##### catch 순서

다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다. try 블록에서 예외가 발생했을 때, 예외를 처리해줄 catch 블록은 위에서부터 차례대로 검색된다.  하위 예외는 상위 예외를 상속했기 때문에 상위 예외 타입도 되기 때문이다. 

